
version: '2'
services:
  mapserver:
    image: mapserver-image
    build:
      context: .
      dockerfile: DockerfileMapserver
    container_name: mapserver-compose
    privileged: true
    shm_size: 25G
    volumes:
      - ./map:/map:ro
      - /tiledata/source/:/tiledata/source/:ro
    hostname: mapserver_composer
    ports:
      - "8080:80"
    tty: true
    command: ["/usr/local/bin/run.sh"]
    networks:
      net:
        ipv4_address: 10.10.0.3
  mapcache:
    image: mapcache-image
    build:
      context: .
      dockerfile: DockerfileMapcache
    container_name: mapcache-compose
    hostname: mapcache_composer
    privileged: true
    shm_size: 25G
    volumes:
      - /tiledata/cache/:/var/www/html/mapcache/cache
      - /tiledata/source/:/tiledata/source/
      - ./mapcache-configs:/var/www/html/mapcache/
    stdin_open: true
    depends_on:
      - "mapserver"
    networks:
      net:
        ipv4_address: 10.10.0.2
    tty: true
  gdal:
    #build from https://github.com/pedros007/mapserver-docker
    image: gdal-image
    container_name: gdal-compose
    hostname: gdal_composer
    privileged: true
    shm_size: 25G
    volumes:
      - /tiledata/source/:/tiledata/source/
      - /tiledata/cache/:/tiledata/cache/
    stdin_open: true
    networks:
      net:
        ipv4_address: 10.10.0.4
    tty: true
  gdal-python:
    #build from https://github.com/ecarrara/docker-python-gdal/blob/master/2.2.1-python2.7/Dockerfile
    image: gdalpython-image
    container_name: gdalpython-compose
    hostname: gdalpython_composer
    privileged: true
    shm_size: 25G
    volumes:
      - /tiledata/source/:/tiledata/source/
      - /tiledata/cache/:/tiledata/cache/
    stdin_open: true
    networks:
      net:
        ipv4_address: 10.10.0.4
    tty: true

networks:
  net:
    driver: bridge
    ipam:
     config:
       - subnet: 10.10.0.0/16
